version: '2'
services:
  db:
    image: mongo:latest
    ports:
    - "27017"  

  app:
    build: .
    environment:
      NODE_ENV: production
      PORT: 80
      SERVICE_NAME: app
      DB_URI: 'mongodb://db:27017/ejemplo'
    links:
    - "db:DB"
    ports:
    - "80"

  lb:
    image: jasonwyatt/nginx-loadbalancer
    links:
    - app
    environment:
      APP_PATH: "/"
      SRC_APP_PATH: "/src"
    ports:
    - "8080:80"