global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'overwritten-default'

    consul_sd_configs:
      - server:   'consul:8500'
        services: ['api', 'eventapp', 'db']

    relabel_configs:
      - source_labels: ['__meta_consul_service']
        regex:         '(.*)'
        target_label:  'job'
        replacement:   '$1'
      - source_labels: ['__meta_consul_node']
        regex:         '(.*)'
        target_label:  'instance'
        replacement:   '$1'
      - source_labels: ['__meta_consul_tags']
        regex:         ',(production|canary),'
        target_label:  'group'
        replacement:   '$1'